name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:

      #
      - name: Pull Docker image
        run: docker pull sarahbadibanga883/cicd-pipeline:latest 

      - name: Delete Old Docker container
        run: docker rm -f cicd-pipeline || true

      - name: Run Docker container
        run: docker run -d --name cicd-pipeline -p 8080:8080 sarahbadibanga883/cicd-pipeline
