name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Docker Hub using PAT (SSO alternative)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build the Docker image
        run: docker build -t sarahbadibanga883/cicd-pipeline .

      - name: Push to Docker Hub
        run: docker push sarahbadibanga883/cicd-pipeline:latest
